/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejo;
import clases.DenominadorCeroException;
import javax.swing.JOptionPane;

/**
 *
 * @author aldair
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtResultadoPDos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtResultadoNDos = new javax.swing.JTextField();
        txtResultadoDDos = new javax.swing.JTextField();
        txtResultadoNUno = new javax.swing.JTextField();
        txtResultadoDUno = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtParteUno = new javax.swing.JTextField();
        cmbOperaciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtResultadoPUno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtParteUnoUno = new javax.swing.JTextField();
        txtParteDos = new javax.swing.JTextField();
        txtParteDosDos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jTextField6.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Operaciones Con Numeros Complejos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 670, -1));

        txtResultadoPDos.setEditable(false);
        jPanel1.add(txtResultadoPDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 50, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Division", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 10));

        txtResultadoNDos.setEditable(false);
        jPanel2.add(txtResultadoNDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 30, 40));

        txtResultadoDDos.setEditable(false);
        jPanel2.add(txtResultadoDDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 30, 40));

        txtResultadoNUno.setEditable(false);
        jPanel2.add(txtResultadoNUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, 40));

        txtResultadoDUno.setEditable(false);
        jPanel2.add(txtResultadoDUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 30, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 30, 10));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("i");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 20, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("+");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/F81F82763.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 180));

        txtParteUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParteUnoActionPerformed(evt);
            }
        });
        txtParteUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParteUnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtParteUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 50));

        cmbOperaciones.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        cmdCalcular.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 220, 60));

        cmdLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("i");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 20, -1));

        txtResultadoPUno.setEditable(false);
        jPanel1.add(txtResultadoPUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 60, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("i");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 20, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("i");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 20, -1));

        txtParteUnoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParteUnoUnoActionPerformed(evt);
            }
        });
        txtParteUnoUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParteUnoUnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtParteUnoUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 50, 50));

        txtParteDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParteDosActionPerformed(evt);
            }
        });
        txtParteDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParteDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtParteDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 50, 50));

        txtParteDosDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParteDosDosActionPerformed(evt);
            }
        });
        txtParteDosDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParteDosDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtParteDosDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/F81F82763.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtParteUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParteUnoActionPerformed
      
    }//GEN-LAST:event_txtParteUnoActionPerformed

    private void txtParteUnoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParteUnoUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParteUnoUnoActionPerformed

    private void txtParteDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParteDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParteDosActionPerformed

    private void txtParteDosDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParteDosDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParteDosDosActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        try {

            int aux1, aux2, aux3, aux4, x;
            int exe;
            Complejo x1, x2, x3;
            
            if(txtParteUno.getText().trim().isEmpty() && txtParteDos.getText().trim().isEmpty() && txtParteUnoUno.getText().trim().isEmpty() && txtParteDosDos.getText().trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "por favor LLENE los campos vacios", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(txtParteUno.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor indique la parte real del primer numero" , "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(txtParteDos.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor indique la parte imaginaria del primer numero" , "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(txtParteUnoUno.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor indique la parte real del segundo numero" , "ERROR", JOptionPane.WARNING_MESSAGE);
            }else if(txtParteDosDos.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor indique la parte imaginaria del segundo numero" , "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{

            exe = cmbOperaciones.getSelectedIndex();
            aux1 = Integer.parseInt(txtParteUno.getText());
            aux2 = Integer.parseInt(txtParteDos.getText());
            aux3 = Integer.parseInt(txtParteUnoUno.getText());
            aux4 = Integer.parseInt(txtParteDosDos.getText());

            x1 = new Complejo(aux1, aux2);
            x2 = new Complejo(aux3, aux4);
            
            
            switch (exe) {
                case 0:
                    x3 = x1.sumar(x2);
                    txtResultadoPUno.setText("" + x3.getParteUno());
                    txtResultadoPDos.setText("" + x3.getParteDos());
                   
                    break;

                case 1:
                    x3 = x1.restar(x2);
                    txtResultadoPUno.setText("" + x3.getParteUno());
                    txtResultadoPDos.setText("" + x3.getParteDos());
                    
                    break;

                case 2:
                    x3 = x1.Multiplicar(x2);
                    txtResultadoPUno.setText("" + x3.getParteUno());
                    txtResultadoPDos.setText("" + x3.getParteDos());
                    
                    break;

                case 3:
                    
                    x3 = x1.Dividir(x2);
                    txtResultadoNUno.setText("" + x3.getParteUno());
                    txtResultadoNDos.setText("" + x3.getParteDos());
                    x = (x2.getParteUno() * x2.getParteUno()) + (x2.getParteDos() * x2.getParteDos());
                    txtResultadoDUno.setText("" + x);
                    txtResultadoDDos.setText("" + x);
                    txtResultadoPUno.setText("");
                    txtResultadoPDos.setText("");
                    
                    break;
            }
            }
        } catch (NumberFormatException k) {
            JOptionPane.showMessageDialog(this, "ERROR en algunos digitos, por favor verifique", "MENSAJE", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:

        txtParteUno.setText("");
        txtParteDos.setText("");
        txtParteUnoUno.setText("");
        txtParteDosDos.setText("");
        txtResultadoNUno.setText("");
        txtResultadoNDos.setText("");
        txtResultadoDUno.setText("");
        txtResultadoDDos.setText("");
        txtResultadoPUno.setText("");
        txtResultadoPDos.setText("");
        cmbOperaciones.setSelectedIndex(0);
        txtParteUno.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtParteUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParteUnoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '-') {
            getToolkit();

            evt.consume();
        }
    }//GEN-LAST:event_txtParteUnoKeyTyped

    private void txtParteUnoUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParteUnoUnoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '-') {
            getToolkit();

            evt.consume();
        }
    }//GEN-LAST:event_txtParteUnoUnoKeyTyped

    private void txtParteDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParteDosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '-') {
            getToolkit();

            evt.consume();
        }
    }//GEN-LAST:event_txtParteDosKeyTyped

    private void txtParteDosDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParteDosDosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '-') {
            getToolkit();

            evt.consume();
        }
    }//GEN-LAST:event_txtParteDosDosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtParteDos;
    private javax.swing.JTextField txtParteDosDos;
    private javax.swing.JTextField txtParteUno;
    private javax.swing.JTextField txtParteUnoUno;
    private javax.swing.JTextField txtResultadoDDos;
    private javax.swing.JTextField txtResultadoDUno;
    private javax.swing.JTextField txtResultadoNDos;
    private javax.swing.JTextField txtResultadoNUno;
    private javax.swing.JTextField txtResultadoPDos;
    private javax.swing.JTextField txtResultadoPUno;
    // End of variables declaration//GEN-END:variables
}
